@startuml

skinparam componentStyle uml2

component [Administracao]
component [Interacao]
component [Recomendacao]
component [Discussao]
component [Tendencia]

[Administracao]<-->[Interacao] : Shared Kernel

[Interacao]<-->[Recomendacao] : Shared Kernel

[Recomendacao]<-->[Tendencia] : Shared Kernel



@enduml
