@startuml

skinparam componentStyle uml2

package "'SalaDeDiscussao' Aggregate" <<Rectangle>> {
	class SalaDeDiscussao <<(A,#fffab8) Aggregate Root>> {
		List<Comentario> comentarios
		SalaId id
		FilmeId filmeId
		void adicionarComentario(Comentario comentario)
	}
	class SalaId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
	class DiscussaoService <<(S,DarkSeaGreen) Service>> {
		void criarSala(FilmeId filmeId)
		void comentarSala(SalaId salaId, Comentario comentario)
	}
}
SalaDeDiscussao --> SalaId : id
legend left
  This bounded context implements the subdomain 'Discussao'.
end legend


@enduml
